version: "3.9"
services:
  ### ===================
  ### APP SERVICE
  ### ===================
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: payment_service
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/app/